### ISSUE TITLE
Automatic Install Script 

### ISSUE THREAD

**Issue by 21tushar** [Matt-FTW/dotfiles#13]
### Did you check existing feature request?

- [X] I have searched the existing requests of the repo

### Is your feature request related to a problem? Please describe.

Sir please make a automatic installation script 

### Describe the solution you'd like

Nothing

### Describe alternatives you've considered

Nothing 

### Additional Context

Nothing

**Comment by 21tushar** [comment]
Request

**Comment by Matt-FTW** [comment]
Hi,
So I had the section in the README for the automatic install script in WIP, but more and more I'm thinking about deleting it. Why?
Maintaining an install script is hard and right now I dont have the time to invest on it. There's the Ansible playbooks I had written down, which serve as kind of an automatic installation, but I would recommend that you use the steps in the manual installation section on the README. Its just like five commands to execute and your done. Be sure to read carefully tho.
