### ISSUE TITLE
🐛 Bug:  obsidian not opening

### ISSUE THREAD

**Issue by xArcGit** [Matt-FTW/dotfiles#20]
### Did you check existing issues?

- [X] I have searched the existing issues of the repo
- [X] I have searched the existing issues of used programs related to this issue
- [X] I have read the [FAQ](https://github.com/Matt-FTW/dotfiles/blob/main/.github/FAQ.md)

### Description of the bug

LOG
> obsidian
Loading main app package /usr/lib/obsidian/obsidian.asar
Checking for update using Github

>

that all 

### Screenshots

![image](https://github.com/user-attachments/assets/ca61c8fa-895b-4c19-a090-c14c685ae8a9)

### Environment

Linux Distro, Linux Version, Hyprland Version...
No change in config are done

**Comment by Matt-FTW** [comment]
Hey!

Did it not open a new window? Try using an app launcher instead of the terminal. Either way, I dont think it is related to the config.
