### ISSUE TITLE
🐛 Bug: Brightness toggle buttons refuse to operate on laptop

### ISSUE THREAD

**Issue by xburrito** [Matt-FTW/dotfiles#23]
### Did you check existing issues?

- [X] I have searched the existing issues of the repo
- [X] I have searched the existing issues of used programs related to this issue
- [X] I have read the [FAQ](https://github.com/Matt-FTW/dotfiles/blob/main/.github/FAQ.md)

### Description of the bug

After the following the guide through a fresh arch installation as well as the post-installation guide, swayOSD refuses to interact with the brightness toggle. I've checked the `swayosd-libinput-backend.service` and it's indeed running. And checked out SwayOSD's reasoning for why it may not be reading the brightness file and modifying it. Stuck from this point onward.

### Environment

Linux Distro: Arch Linux x86_64  
Linux Version: Linux 6.10.10-arch1-1
Hyprland Version: v0.43.0
Hardware: Framework Laptop 13 AMD _AMD Ryzen 7040Series_
AMD drivers are up to date (dunno if that matters for this problem tho)

**Comment by Matt-FTW** [comment]
Hey,

I dont think is an issue with the dotfiles themselves, tho I cannot even replicate it because I dont have a laptop :( 

If you checked the SwayOSD docs and still doesnt work I would open a new issue over there. 

I would also try to use [brightnessctl](https://github.com/Hummer12007/brightnessctl) and see if it works.

Sorry about it buddy!

**Comment by xburrito** [comment]
Wow, installing `brightnessctl` 100% fixed those toggle buttons. Amazing~

**Comment by Matt-FTW** [comment]
I found the reason why it works with brightnessctl installed. On [this pr](https://github.com/ErikReider/SwayOSD/pull/60) they introduced a new backend for brightnessctl using the --brightness flag, the one is setup on the binds config file.

I'd add it to the README
