### ISSUE TITLE
🐛 Bug: kitty

### ISSUE THREAD

**Issue by tim1737** [Matt-FTW/dotfiles#26]
### Did you check existing issues?

- [X] I have searched the existing issues of the repo
- [X] I have searched the existing issues of used programs related to this issue
- [X] I have read the [FAQ](https://github.com/Matt-FTW/dotfiles/blob/main/.github/FAQ.md)

### Description of the bug

Please Help, how to disable the display of kitty pictures from above when creating a new session, I can't find it in any way. I'm sorry for the wrong thread

### Environment

Arch, last versions

**Comment by Matt-FTW** [comment]
Hey!,

Delete [this line](https://github.com/Matt-FTW/dotfiles/blob/0575eda440d1620556b3749d81a506b6f8177a0e/.config/fish/functions/fish_greeting.fish#L3) and you're done :)

**Comment by tim1737** [comment]
Thx
