### ISSUE TITLE
🐛 Bug: Its NOT a bug! Nice Config, just a notice (? 

### ISSUE THREAD

**Issue by codeskin-r** [Matt-FTW/dotfiles#29]
### Did you check existing issues?

- [X] I have searched the existing issues of the repo
- [X] I have searched the existing issues of used programs related to this issue
- [X] I have read the [FAQ](https://github.com/Matt-FTW/dotfiles/blob/main/.github/FAQ.md)

### Description of the bug

**Hello! It's not a bug, it was to warn you that the hyperlinks within the Vercel post-installation tutorial are not working! Luck!**

### Environment

EndeavourOS Gnome + Hyprland

**Comment by Matt-FTW** [comment]
[Fixed](https://github.com/Matt-FTW/dotfiles-docs/commit/96cbcd3fc90225d12c0ff8aaebd28cae3a969931), thanks for the report!
