### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by NicolaiU** [Matt-FTW/dotfiles#33]
### Did you check existing issues?

- [X] I have searched the existing issues of the repo
- [X] I have searched the existing issues of used programs related to this issue
- [X] I have read the [FAQ](https://github.com/Matt-FTW/dotfiles/blob/main/.github/FAQ.md)

### Description of the bug

When i ran hyprland i got a message saying i needed to update hyprpm and when i try to do that i get error code 4 for hyprpm.

### Environment

Linux Distro, Linux Version, Hyprland Version...
Arch hyprland

**Comment by Matt-FTW** [comment]
Hey, that's and issue related with Hyprland and not the dotfiles. Report the issue to their repo.
