### ISSUE TITLE
🐛 Bug: with command "sudo pacman -S" suggestions not showin correclty

### ISSUE THREAD

**Issue by Ayanashi** [Matt-FTW/dotfiles#34]
### Did you check existing issues?

- [X] I have searched the existing issues of the repo
- [X] I have searched the existing issues of used programs related to this issue
- [X] I have read the [FAQ](https://github.com/Matt-FTW/dotfiles/blob/main/.github/FAQ.md)

### Description of the bug

little issue with suggestion on pacman -S but with yay -S show correcly
already installed all packages and configs works done without any error output
runnin on 

### Screenshots

**sudo pacman -S**
![captura-2024-11-27-1732737211](https://github.com/user-attachments/assets/a3997d08-a182-4720-9554-33495530536f)
**yay -S**
![captura-2024-11-27-1732739319](https://github.com/user-attachments/assets/813e64f8-89c0-49b0-81ea-10f1b89984fb)

### Environment

_Archlinux 6.12.1
kitty 0.37
fish version 3.7.1_

**Comment by Matt-FTW** [comment]
Thats and issue related to the fish.fzf plugin. I'd recommend you to use yay instead of pacman anyway.

**Comment by Ayanashi** [comment]
> Thats and issue related to the fzf.fish plugin. I'd recommend you to use yay instead of pacman anyway.

umh i use yay too but pacman also somethimes any tips for the configuration of fzf? maybe i need check out somethin in particular?

**Comment by Matt-FTW** [comment]
There's no need to use pacman with yay installed. You can create a pr with the fix for the [fzf.fish plugin](https://github.com/PatrickF1/fzf.fish) if you know where's the issue at, wait for a pr of another person or a fix from the developer itself.

**Comment by Ayanashi** [comment]
let me check, 'cause maybe i have two fzf package installed from patrick and yours and maybe this get some conflict..

**Comment by Ayanashi** [comment]
interesting the issue persist without fzf so this is very weird rn

**Comment by Matt-FTW** [comment]
Yeah, I have it as well with the autompletion engine of fish. Maybe there's an issue with the completion source file of pacman. I'd recommend to create a new issue over on the fish repo.

**Comment by Ayanashi** [comment]
with command 'complete --erase --command pacman' the issue is gone, anyway i create a new completition for pacman and added to fzf

```
function __fish_complete_pacman_packages
        pacman -Sl | awk '{print $2}' # Elenca i pacchetti disponibili
    end

    complete -c pacman -f -a "(__fish_complete_pacman_packages)" \
        -d "Pacman package names"

function __fish_complete_pacman_with_fzf
    pacman -Sl | fzf --preview 'pacman -Si {1}' | awk '{print $2}'
end

complete -c pacman -f -a "(__fish_complete_pacman_with_fzf)" \
    -d "Interactive search with fzf"

```
is not perfect anyway have some issue with autocompletion sometimes, what do you think some suggestions?

**Comment by Ayanashi** [comment]
another option is download  the completitions from fish source for pacman with the command "curl -o ~/.config/fish/completions/pacman.fish https://raw.githubusercontent.com/fish-shell/fish-shell/master/share/completions/pacman.fish" and edit and config with fzf

**Comment by Ayanashi** [comment]
> with command 'complete --erase --command pacman' the issue is gone, anyway i create a new completition for pacman and added to fzf
> 
> ```
> function __fish_complete_pacman_packages
>         pacman -Sl | awk '{print $2}' # Elenca i pacchetti disponibili
>     end
> 
>     complete -c pacman -f -a "(__fish_complete_pacman_packages)" \
>         -d "Pacman package names"
> 
> function __fish_complete_pacman_with_fzf
>     pacman -Sl | fzf --preview 'pacman -Si {1}' | awk '{print $2}'
> end
> 
> complete -c pacman -f -a "(__fish_complete_pacman_with_fzf)" \
>     -d "Interactive search with fzf"
> ```
> 
> is not perfect anyway have some issue with autocompletion sometimes, what do you think some suggestions?
edited function with complete command
`function __fish_complete_pacman_with_fzf
    # Get a list of available packages and use fzf for selection
    set selected_package (pacman -Sl | fzf --preview 'pacman -Si {1}' | awk '{print $2}')

    # If a package was selected, update the command line
    if test -n "$selected_package"
        commandline -t -- "$selected_package"
    end
end

complete -c pacman -f -a "(__fish_complete_pacman_with_fzf)" \
    -d "Interactive search with fzf"
`

**Comment by Matt-FTW** [comment]
I think this is better to have locally instead of upstream. I'll make sure to point out to your solution for anyone who wants to.

**Comment by Ayanashi** [comment]
> I think this is better to have locally instead of upstream. I'll make sure to point out to your solution for anyone who wants to.

the solution is not perfect and cause some issues
